### ISSUE TITLE
Bug with CDN and compression in Chrome

### ISSUE THREAD

**Issue by Onore** [MaxCDN/bootstrapcdn#1267] opened 2019-01-26 09:51 UTC
Hello.

1. https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css
DevTools Network download **without compression 150 Kb**
PageSpeed Lighthouse -- 20Kb

2. https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/css/bootstrap.min.css
DevTools Network download -- 20 Kb
PageSpeed Lighthouse -- 20Kb

3. https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css
The same  as #2.

Example url: https://techhome.kiev.ua
Latest Chrome.

**Comment by XhmikosR** [comment] 2019-01-26 09:52
Not sure what you mean?

**Comment by Onore** [comment] 2019-01-26 10:05
![Image of Bug](https://techhome.kiev.ua/bug.jpg)

**Comment by XhmikosR** [comment] 2019-01-26 10:08
I can't see it being sent uncompressed here.


```
$ curl -ILl -H "Accept-Encoding: gzip,deflate" https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css
HTTP/2 200
date: Sat, 26 Jan 2019 10:07:00 GMT
accept-ranges: bytes
etag: "1545419987"
content-encoding: gzip
content-length: 22972
content-type: text/css; charset=utf-8
last-modified: Fri, 21 Dec 2018 19:19:47 GMT
x-hello-human: Say hello back! @getBootstrapCDN on Twitter
access-control-allow-origin: *
vary: Accept-Encoding
x-cache: HIT
timing-allow-origin: *
cache-control: public, max-age=31536000
```

Try the above command 3-4 times just in case it's uncached otherwise:

>If this is a CDN service related issue (timeouts, slowness, ssl), please fill out this form so we can debug it: <https://goo.gl/forms/u2SFZS44ZGIM7yP82>

**Comment by Onore** [comment] 2019-01-26 10:15
1. I have disabled cache in DevTool
2. If Chrome works like shown in screenshot above any test (without Chrome) does not matter.
I dont know how, but simple way is a measure the traffic of page by 3-d party tools and result in devtools

**Comment by XhmikosR** [comment] 2019-01-26 10:16
Well, unless you follow the above, there's nothing I can do.

**Comment by XhmikosR** [comment] 2019-01-26 10:16
Also, with cache I'm referring to the POP's cache. gzip doesn't happen on the first request.

**Comment by Onore** [comment] 2019-01-26 10:35
I dont know about POP`s, sorry.
But you can reproduce the problem on you pc in less than 5 minutes.
**Or do you have not the same result like in my screenshoot?**

**Comment by XhmikosR** [comment] 2019-01-26 10:44
No, I can't reproduce hence why https://github.com/MaxCDN/bootstrapcdn/issues/1267#issuecomment-457818881

Please do the above.

**Comment by Onore** [comment] 2019-01-26 11:42
TP/2 200
date: Sat, 26 Jan 2019 11:39:45 GMT  
accept-ranges: bytes   
etag: "1545419987"    
content-encoding: gzip    
content-length: 22972  
 content-type: text/css; charset=utf-8  
last-modified: Fri, 21 Dec 2018 19:19:47 GMT 
x-hello-human: Say hello back! @getBootstrapCDN on Twitter 
access-control-allow-origin: *    
vary: Accept-Encoding        
x-cache: HIT          
timing-allow-origin: *
cache-control: public, max-age=31536000
--








--


``

TP/2 200                                                                         date: Sat, 26 Jan 2019 11:39:45 GMT                                              accept-ranges: bytes                                                             etag: "1545419987"                                                               content-encoding: gzip                                                           content-length: 22972                                                            content-type: text/css; charset=utf-8                                            last-modified: Fri, 21 Dec 2018 19:19:47 GMT                                     x-hello-human: Say hello back! @getBootstrapCDN on Twitter                       access-control-allow-origin: *                                                   vary: Accept-Encoding                                                            x-cache: HIT                                                                     timing-allow-origin: *                                                           cache-control: public, max-age=31536000
--

TP/2 200                                                                         date: Sat, 26 Jan 2019 11:39:45 GMT                                              accept-ranges: bytes                                                             etag: "1545419987"                                                               content-encoding: gzip                                                           content-length: 22972                                                            content-type: text/css; charset=utf-8                                            last-modified: Fri, 21 Dec 2018 19:19:47 GMT                                     x-hello-human: Say hello back! @getBootstrapCDN on Twitter                       access-control-allow-origin: *                                                   vary: Accept-Encoding                                                            x-cache: HIT                                                                     timing-allow-origin: *                                                           cache-control: public, max-age=31536000
--

**Comment by XhmikosR** [comment] 2019-01-26 12:43
As you can see from your output, it is compressed.

**Comment by Onore** [comment] 2019-02-01 13:41
Ok ) But I said that Chrome think differently. @DevTools Network download without compression 150 Kb@

**Comment by XhmikosR** [comment] 2019-02-01 13:42
Well, in that case

>If this is a CDN service related issue (timeouts, slowness, ssl), please fill out this form so we can debug it: https://goo.gl/forms/u2SFZS44ZGIM7yP82

**Comment by XhmikosR** [comment] 2019-03-25 10:31
Closing since like I mention above, the only way for such issues to be solved is for the Google Form to be filled with the needed info. And also I can't reproduce it here.

Keep in mind that you might hit an edge case, where the origin you are hitting (hence why I insist for the form info) might not have the gzipped file on first request, but will have it after a couple of requests and then it'll be cached.

**Closed by XhmikosR** 2019-03-25 10:31 UTC
